[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

# Pretty URLs para legales (si enlazas /privacidad/, /legal/, /cookies/)
[[redirects]]
  from = "/privacidad.html"
  to = "/privacidad/"
  status = 301

[[redirects]]
  from = "/legal.html"
  to = "/legal/"
  status = 301

[[redirects]]
  from = "/cookies.html"
  to = "/cookies/"
  status = 301

# (Opcional) Si antes usabas /quien-soy/, redirige a la nueva ruta con guion bajo
[[redirects]]
  from = "/quien-soy/"
  to = "/quien_soy/"
  status = 301

# Cache largo para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para imágenes locales
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
