# ============================
# Build
# ============================
[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# ============================
# Functions
# ============================
[functions]
  node_bundler = "esbuild"

[functions."submission-created"]
  external_node_modules = ["nodemailer"]

# ============================
# Redirects (orden importa)
# ============================

# 0) Redirecciones de host → dominio canónico + HTTPS (un único salto)
#    - http sin www   → https raíz
#    - http con www   → https raíz
#    - https con www  → https raíz
#    - subdominio Netlify → https raíz
[[redirects]]
  from = "http://nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nuriazardoyalasheras.netlify.app/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

# 1) .html → versión / (regla genérica; evita listar página a página)
#    Ej.: /servicios.html → /servicios/
[[redirects]]
  from = "/:page.html"
  to   = "/:page/"
  status = 301

# 2) Normalización legacy (guion_bajo → guiones)
[[redirects]]
  from = "/quien_soy/"
  to   = "/quien-soy/"
  status = 301

[[redirects]]
  from = "/quien_soy.html"
  to   = "/quien-soy/"
  status = 301

[[redirects]]
  from = "/pide_tu_cita/"
  to   = "/pide-tu-cita/"
  status = 301

[[redirects]]
  from = "/pide_tu_cita.html"
  to   = "/pide-tu-cita/"
  status = 301

# (Opcional pero recomendable) Normaliza algunas rutas "sin slash" a "con slash"
# para evitar que GSC lo marque: /privacidad → /privacidad/ (un salto controlado)
# Añade aquí solo las secciones principales si GSC las señala.
[[redirects]]
  from = "/privacidad"
  to   = "/privacidad/"
  status = 301

[[redirects]]
  from = "/servicios"
  to   = "/servicios/"
  status = 301

# ============================
# Headers (seguridad + caché)
# ============================
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache largo para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para imágenes locales
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tipos explícitos
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
