[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  # Evita pasos innecesarios en la instalación de npm y reduce ruido de logs
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# Empaquetado de Functions más rápido
[functions]
  node_bundler = "esbuild"

# Si alguna function usa módulos que prefieres NO bundlear (como nodemailer), decláralos aquí:
[functions."submission-created"]
  external_node_modules = ["nodemailer"]

# ---------------------------
# Pretty URLs (.html → /)
# ---------------------------
[[redirects]]
  from = "/privacidad.html"
  to = "/privacidad/"
  status = 301

[[redirects]]
  from = "/legal.html"
  to = "/legal/"
  status = 301

[[redirects]]
  from = "/cookies.html"
  to = "/cookies/"
  status = 301

[[redirects]]
  from = "/servicios.html"
  to = "/servicios/"
  status = 301

[[redirects]]
  from = "/contacto.html"
  to = "/contacto/"
  status = 301

[[redirects]]
  from = "/gracias.html"
  to = "/gracias/"
  status = 301

[[redirects]]
  from = "/recetas.html"
  to = "/recetas/"
  status = 301

[[redirects]]
  from = "/blog.html"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/buscador.html"
  to = "/buscador/"
  status = 301

[[redirects]]
  from = "/quien-soy.html"
  to = "/quien-soy/"
  status = 301

[[redirects]]
  from = "/pide-tu-cita.html"
  to = "/pide-tu-cita/"
  status = 301

# ------------------------------------
# Legacy: guion_bajo → guiones (301)
# ------------------------------------
[[redirects]]
  from = "/quien_soy/"
  to = "/quien-soy/"
  status = 301

[[redirects]]
  from = "/quien_soy.html"
  to = "/quien-soy/"
  status = 301

[[redirects]]
  from = "/pide_tu_cita/"
  to = "/pide-tu-cita/"
  status = 301

[[redirects]]
  from = "/pide_tu_cita.html"
  to = "/pide-tu-cita/"
  status = 301

# ------------------------------------
# Canonicalización de dominio (301)
# ------------------------------------
[[redirects]]
  from = "http://nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.nuriazardoya.es/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

# Redirige el subdominio de Netlify al dominio final
[[redirects]]
  from = "https://nuriazardoyalasheras.netlify.app/*"
  to = "https://nuriazardoya.es/:splat"
  status = 301
  force = true

# ---------------------------
# Headers de seguridad
# ---------------------------
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache largo para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para imágenes locales
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-cache"

