[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  # Evita pasos innecesarios en la instalación de npm y reduce ruido de logs
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# Empaquetado de Functions más rápido
[functions]
  node_bundler = "esbuild"

# Si alguna function usa módulos que prefieres NO bundlear (como nodemailer), decláralos aquí:
[functions."submission-created"]
  external_node_modules = ["nodemailer"]

# Pretty URLs para legales
[[redirects]]
  from = "/privacidad.html"
  to = "/privacidad/"
  status = 301

[[redirects]]
  from = "/legal.html"
  to = "/legal/"
  status = 301

[[redirects]]
  from = "/cookies.html"
  to = "/cookies/"
  status = 301

# Si antes usabas /quien-soy/, redirige a la nueva ruta
[[redirects]]
  from = "/quien-soy/"
  to = "/quien_soy/"
  status = 301

# Cache largo para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache largo para imágenes locales
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Para redirigir la primera visita
[[edge_functions]]
function = "lang-redirect"
path = "/*"

